/**
 * radicals_bilingual.json 生成スクリプト
 * 477件の部首データを日英バイリンガル形式で出力
 */

import * as fs from "fs";
import * as path from "path";

interface KanjiDetail {
  kanji: string;
  radicals?: string[];
}

interface RadicalBilingual {
  id: number;
  root: string;
  radical_name_en: string;
  radical_name_ja: string;
  description_en: string;
  description_ja: string;
}

// 英語→日本語部首名マッピング（主要な部首）
const RADICAL_NAME_MAP: Record<string, { ja: string; root: string; desc_ja: string; desc_en: string }> = {
  // 基本的な部首
  "Water": { ja: "さんずい", root: "水", desc_ja: "水に関連する漢字の部首", desc_en: "Radical for water-related kanji" },
  "Person": { ja: "にんべん", root: "人", desc_ja: "人に関連する漢字の部首", desc_en: "Radical for person-related kanji" },
  "Tree": { ja: "きへん", root: "木", desc_ja: "木に関連する漢字の部首", desc_en: "Radical for tree-related kanji" },
  "Hand": { ja: "てへん", root: "手", desc_ja: "手に関連する漢字の部首", desc_en: "Radical for hand-related kanji" },
  "Heart": { ja: "こころ・りっしんべん", root: "心", desc_ja: "心や感情に関連する漢字の部首", desc_en: "Radical for heart/emotion-related kanji" },
  "Sun": { ja: "ひへん・にちへん", root: "日", desc_ja: "太陽や時間に関連する漢字の部首", desc_en: "Radical for sun/time-related kanji" },
  "Moon": { ja: "つきへん", root: "月", desc_ja: "月や肉に関連する漢字の部首", desc_en: "Radical for moon/flesh-related kanji" },
  "Mouth": { ja: "くちへん", root: "口", desc_ja: "口に関連する漢字の部首", desc_en: "Radical for mouth-related kanji" },
  "Earth": { ja: "つちへん", root: "土", desc_ja: "土地に関連する漢字の部首", desc_en: "Radical for earth-related kanji" },
  "Fire": { ja: "ひへん・れっか", root: "火", desc_ja: "火に関連する漢字の部首", desc_en: "Radical for fire-related kanji" },
  "Gold": { ja: "かねへん", root: "金", desc_ja: "金属に関連する漢字の部首", desc_en: "Radical for metal-related kanji" },
  "Word": { ja: "ごんべん", root: "言", desc_ja: "言葉に関連する漢字の部首", desc_en: "Radical for speech-related kanji" },
  "Speech": { ja: "ごんべん", root: "言", desc_ja: "言葉や話すことに関連する漢字の部首", desc_en: "Radical for speech-related kanji" },
  "Say": { ja: "ごんべん", root: "言", desc_ja: "言葉や話すことに関連する漢字の部首", desc_en: "Radical for speech-related kanji" },
  "Eye": { ja: "めへん", root: "目", desc_ja: "目に関連する漢字の部首", desc_en: "Radical for eye-related kanji" },
  "Foot": { ja: "あしへん", root: "足", desc_ja: "足に関連する漢字の部首", desc_en: "Radical for foot-related kanji" },
  "Walk": { ja: "しんにょう", root: "辶", desc_ja: "歩くことや道に関連する漢字の部首", desc_en: "Radical for walking/road-related kanji" },
  "Road": { ja: "しんにょう", root: "辶", desc_ja: "道に関連する漢字の部首", desc_en: "Radical for road-related kanji" },
  "Mountain": { ja: "やまへん", root: "山", desc_ja: "山に関連する漢字の部首", desc_en: "Radical for mountain-related kanji" },
  "River": { ja: "さんずい", root: "川", desc_ja: "川に関連する漢字の部首", desc_en: "Radical for river-related kanji" },
  "Rain": { ja: "あめかんむり", root: "雨", desc_ja: "天気や雨に関連する漢字の部首", desc_en: "Radical for rain/weather-related kanji" },
  "Grass": { ja: "くさかんむり", root: "艹", desc_ja: "植物に関連する漢字の部首", desc_en: "Radical for grass/plant-related kanji" },
  "Flower": { ja: "くさかんむり", root: "艹", desc_ja: "花や植物に関連する漢字の部首", desc_en: "Radical for flower/plant-related kanji" },
  "Rice": { ja: "こめへん", root: "米", desc_ja: "米に関連する漢字の部首", desc_en: "Radical for rice-related kanji" },
  "Rice Paddy": { ja: "たへん", root: "田", desc_ja: "田んぼに関連する漢字の部首", desc_en: "Radical for rice paddy-related kanji" },
  "Thread": { ja: "いとへん", root: "糸", desc_ja: "糸や繊維に関連する漢字の部首", desc_en: "Radical for thread-related kanji" },
  "Silk": { ja: "いとへん", root: "糸", desc_ja: "糸や絹に関連する漢字の部首", desc_en: "Radical for silk-related kanji" },
  "Clothes": { ja: "ころもへん", root: "衣", desc_ja: "衣服に関連する漢字の部首", desc_en: "Radical for clothes-related kanji" },
  "Food": { ja: "しょくへん", root: "食", desc_ja: "食べ物に関連する漢字の部首", desc_en: "Radical for food-related kanji" },
  "Eat": { ja: "しょくへん", root: "食", desc_ja: "食べることに関連する漢字の部首", desc_en: "Radical for eating-related kanji" },
  "Horse": { ja: "うまへん", root: "馬", desc_ja: "馬に関連する漢字の部首", desc_en: "Radical for horse-related kanji" },
  "Fish": { ja: "うおへん", root: "魚", desc_ja: "魚に関連する漢字の部首", desc_en: "Radical for fish-related kanji" },
  "Bird": { ja: "とりへん", root: "鳥", desc_ja: "鳥に関連する漢字の部首", desc_en: "Radical for bird-related kanji" },
  "Dog": { ja: "けものへん", root: "犬", desc_ja: "犬や動物に関連する漢字の部首", desc_en: "Radical for dog-related kanji" },
  "Cow": { ja: "うしへん", root: "牛", desc_ja: "牛に関連する漢字の部首", desc_en: "Radical for cow-related kanji" },
  "Sheep": { ja: "ひつじへん", root: "羊", desc_ja: "羊に関連する漢字の部首", desc_en: "Radical for sheep-related kanji" },
  "Shell": { ja: "かいへん", root: "貝", desc_ja: "貝や財産に関連する漢字の部首", desc_en: "Radical for shell/money-related kanji" },
  "Stone": { ja: "いしへん", root: "石", desc_ja: "石に関連する漢字の部首", desc_en: "Radical for stone-related kanji" },
  "Roof": { ja: "うかんむり", root: "宀", desc_ja: "屋根や建物に関連する漢字の部首", desc_en: "Radical for roof/building-related kanji" },
  "House": { ja: "うかんむり", root: "宀", desc_ja: "家に関連する漢字の部首", desc_en: "Radical for house-related kanji" },
  "Door": { ja: "もんがまえ", root: "門", desc_ja: "門や扉に関連する漢字の部首", desc_en: "Radical for door/gate-related kanji" },
  "Gate": { ja: "もんがまえ", root: "門", desc_ja: "門に関連する漢字の部首", desc_en: "Radical for gate-related kanji" },
  "Woman": { ja: "おんなへん", root: "女", desc_ja: "女性に関連する漢字の部首", desc_en: "Radical for woman-related kanji" },
  "Child": { ja: "こへん", root: "子", desc_ja: "子供に関連する漢字の部首", desc_en: "Radical for child-related kanji" },
  "King": { ja: "おうへん・たまへん", root: "王", desc_ja: "王や玉に関連する漢字の部首", desc_en: "Radical for king/jewel-related kanji" },
  "Jewel": { ja: "たまへん", root: "玉", desc_ja: "宝石に関連する漢字の部首", desc_en: "Radical for jewel-related kanji" },
  "Sword": { ja: "りっとう", root: "刂", desc_ja: "刀に関連する漢字の部首", desc_en: "Radical for sword-related kanji" },
  "Knife": { ja: "りっとう", root: "刂", desc_ja: "刃物に関連する漢字の部首", desc_en: "Radical for knife-related kanji" },
  "Power": { ja: "ちからへん", root: "力", desc_ja: "力に関連する漢字の部首", desc_en: "Radical for power-related kanji" },
  "Strength": { ja: "ちからへん", root: "力", desc_ja: "力に関連する漢字の部首", desc_en: "Radical for strength-related kanji" },
  "Field": { ja: "たへん", root: "田", desc_ja: "田んぼに関連する漢字の部首", desc_en: "Radical for field-related kanji" },
  "Net": { ja: "あみがしら", root: "网", desc_ja: "網に関連する漢字の部首", desc_en: "Radical for net-related kanji" },
  "Bamboo": { ja: "たけかんむり", root: "竹", desc_ja: "竹に関連する漢字の部首", desc_en: "Radical for bamboo-related kanji" },
  "Alcohol": { ja: "さけへん", root: "酉", desc_ja: "酒に関連する漢字の部首", desc_en: "Radical for alcohol-related kanji" },
  "Sake": { ja: "さけへん", root: "酉", desc_ja: "酒に関連する漢字の部首", desc_en: "Radical for sake-related kanji" },
  "Bow": { ja: "ゆみへん", root: "弓", desc_ja: "弓に関連する漢字の部首", desc_en: "Radical for bow-related kanji" },
  "Arrow": { ja: "やへん", root: "矢", desc_ja: "矢に関連する漢字の部首", desc_en: "Radical for arrow-related kanji" },
  "Car": { ja: "くるまへん", root: "車", desc_ja: "車に関連する漢字の部首", desc_en: "Radical for car/vehicle-related kanji" },
  "Cart": { ja: "くるまへん", root: "車", desc_ja: "車に関連する漢字の部首", desc_en: "Radical for cart-related kanji" },
  "Boat": { ja: "ふねへん", root: "舟", desc_ja: "船に関連する漢字の部首", desc_en: "Radical for boat-related kanji" },
  "Ship": { ja: "ふねへん", root: "舟", desc_ja: "船に関連する漢字の部首", desc_en: "Radical for ship-related kanji" },
  "Bone": { ja: "ほねへん", root: "骨", desc_ja: "骨に関連する漢字の部首", desc_en: "Radical for bone-related kanji" },
  "Flesh": { ja: "にくづき", root: "月", desc_ja: "体や肉に関連する漢字の部首", desc_en: "Radical for flesh/body-related kanji" },
  "Body": { ja: "にくづき", root: "月", desc_ja: "体に関連する漢字の部首", desc_en: "Radical for body-related kanji" },
  "Spirit": { ja: "しめすへん", root: "示", desc_ja: "神や祭りに関連する漢字の部首", desc_en: "Radical for spirit/ritual-related kanji" },
  "Altar": { ja: "しめすへん", root: "示", desc_ja: "祭壇に関連する漢字の部首", desc_en: "Radical for altar-related kanji" },
  "Rain": { ja: "あめかんむり", root: "雨", desc_ja: "雨や天気に関連する漢字の部首", desc_en: "Radical for rain-related kanji" },
  "Wind": { ja: "かぜへん", root: "風", desc_ja: "風に関連する漢字の部首", desc_en: "Radical for wind-related kanji" },
  "Sound": { ja: "おとへん", root: "音", desc_ja: "音に関連する漢字の部首", desc_en: "Radical for sound-related kanji" },
  "Music": { ja: "おとへん", root: "音", desc_ja: "音楽に関連する漢字の部首", desc_en: "Radical for music-related kanji" },
  "Color": { ja: "いろへん", root: "色", desc_ja: "色に関連する漢字の部首", desc_en: "Radical for color-related kanji" },
  "White": { ja: "しろ", root: "白", desc_ja: "白に関連する漢字の部首", desc_en: "Radical for white-related kanji" },
  "Black": { ja: "くろ", root: "黒", desc_ja: "黒に関連する漢字の部首", desc_en: "Radical for black-related kanji" },
  "Red": { ja: "あか", root: "赤", desc_ja: "赤に関連する漢字の部首", desc_en: "Radical for red-related kanji" },
  "Blue": { ja: "あお", root: "青", desc_ja: "青に関連する漢字の部首", desc_en: "Radical for blue-related kanji" },
  "Big": { ja: "だい", root: "大", desc_ja: "大きさに関連する漢字の部首", desc_en: "Radical for big/large-related kanji" },
  "Small": { ja: "しょう", root: "小", desc_ja: "小ささに関連する漢字の部首", desc_en: "Radical for small-related kanji" },
  "One": { ja: "いち", root: "一", desc_ja: "数字の一に関連する漢字の部首", desc_en: "Radical for one-related kanji" },
  "Two": { ja: "に", root: "二", desc_ja: "数字の二に関連する漢字の部首", desc_en: "Radical for two-related kanji" },
  "Three": { ja: "さん", root: "三", desc_ja: "数字の三に関連する漢字の部首", desc_en: "Radical for three-related kanji" },
  "Ten": { ja: "じゅう", root: "十", desc_ja: "数字の十に関連する漢字の部首", desc_en: "Radical for ten-related kanji" },
  "Hundred": { ja: "ひゃく", root: "百", desc_ja: "数字の百に関連する漢字の部首", desc_en: "Radical for hundred-related kanji" },
  "Thousand": { ja: "せん", root: "千", desc_ja: "数字の千に関連する漢字の部首", desc_en: "Radical for thousand-related kanji" },
  "Stop": { ja: "とめる", root: "止", desc_ja: "止まることに関連する漢字の部首", desc_en: "Radical for stop-related kanji" },
  "Death": { ja: "がつ", root: "歹", desc_ja: "死に関連する漢字の部首", desc_en: "Radical for death-related kanji" },
  "Weapon": { ja: "ほこづくり", root: "殳", desc_ja: "武器に関連する漢字の部首", desc_en: "Radical for weapon-related kanji" },
  "Compare": { ja: "くらべる", root: "比", desc_ja: "比較に関連する漢字の部首", desc_en: "Radical for compare-related kanji" },
  "Fur": { ja: "けがわ", root: "毛", desc_ja: "毛に関連する漢字の部首", desc_en: "Radical for fur-related kanji" },
  "Hair": { ja: "かみ", root: "髟", desc_ja: "髪に関連する漢字の部首", desc_en: "Radical for hair-related kanji" },
  "Leather": { ja: "かわへん", root: "革", desc_ja: "革に関連する漢字の部首", desc_en: "Radical for leather-related kanji" },
  "Skin": { ja: "かわへん", root: "皮", desc_ja: "皮膚に関連する漢字の部首", desc_en: "Radical for skin-related kanji" },
  "Tooth": { ja: "は", root: "歯", desc_ja: "歯に関連する漢字の部首", desc_en: "Radical for tooth-related kanji" },
  "Tongue": { ja: "した", root: "舌", desc_ja: "舌に関連する漢字の部首", desc_en: "Radical for tongue-related kanji" },
  "Nose": { ja: "はな", root: "鼻", desc_ja: "鼻に関連する漢字の部首", desc_en: "Radical for nose-related kanji" },
  "Ear": { ja: "みみ", root: "耳", desc_ja: "耳に関連する漢字の部首", desc_en: "Radical for ear-related kanji" },
  "Face": { ja: "かお", root: "面", desc_ja: "顔に関連する漢字の部首", desc_en: "Radical for face-related kanji" },
  "Head": { ja: "あたま", root: "頁", desc_ja: "頭に関連する漢字の部首", desc_en: "Radical for head-related kanji" },
  "Neck": { ja: "くび", root: "首", desc_ja: "首に関連する漢字の部首", desc_en: "Radical for neck-related kanji" },
  "Wing": { ja: "はね", root: "羽", desc_ja: "羽に関連する漢字の部首", desc_en: "Radical for wing-related kanji" },
  "Feather": { ja: "はねへん", root: "羽", desc_ja: "羽毛に関連する漢字の部首", desc_en: "Radical for feather-related kanji" },
  "Leg": { ja: "あし", root: "足", desc_ja: "足に関連する漢字の部首", desc_en: "Radical for leg-related kanji" },
  "Claw": { ja: "つめ", root: "爪", desc_ja: "爪に関連する漢字の部首", desc_en: "Radical for claw-related kanji" },
  "Horn": { ja: "つの", root: "角", desc_ja: "角に関連する漢字の部首", desc_en: "Radical for horn-related kanji" },
  "Tiger": { ja: "とらへん", root: "虎", desc_ja: "虎に関連する漢字の部首", desc_en: "Radical for tiger-related kanji" },
  "Snake": { ja: "へびへん", root: "虫", desc_ja: "蛇に関連する漢字の部首", desc_en: "Radical for snake-related kanji" },
  "Insect": { ja: "むしへん", root: "虫", desc_ja: "虫に関連する漢字の部首", desc_en: "Radical for insect-related kanji" },
  "Bug": { ja: "むしへん", root: "虫", desc_ja: "虫に関連する漢字の部首", desc_en: "Radical for bug-related kanji" },
  "Turtle": { ja: "かめ", root: "亀", desc_ja: "亀に関連する漢字の部首", desc_en: "Radical for turtle-related kanji" },
  "Frog": { ja: "かえる", root: "黽", desc_ja: "蛙に関連する漢字の部首", desc_en: "Radical for frog-related kanji" },
  "Deer": { ja: "しか", root: "鹿", desc_ja: "鹿に関連する漢字の部首", desc_en: "Radical for deer-related kanji" },
  "Pig": { ja: "ぶた", root: "豕", desc_ja: "豚に関連する漢字の部首", desc_en: "Radical for pig-related kanji" },
  "Rat": { ja: "ねずみ", root: "鼠", desc_ja: "ネズミに関連する漢字の部首", desc_en: "Radical for rat-related kanji" },
  "Fly": { ja: "とぶ", root: "飛", desc_ja: "飛ぶことに関連する漢字の部首", desc_en: "Radical for fly-related kanji" },
  "Run": { ja: "はしる", root: "走", desc_ja: "走ることに関連する漢字の部首", desc_en: "Radical for run-related kanji" },
  "Stand": { ja: "たつ", root: "立", desc_ja: "立つことに関連する漢字の部首", desc_en: "Radical for stand-related kanji" },
  "Sit": { ja: "すわる", root: "坐", desc_ja: "座ることに関連する漢字の部首", desc_en: "Radical for sit-related kanji" },
  "See": { ja: "みる", root: "見", desc_ja: "見ることに関連する漢字の部首", desc_en: "Radical for see-related kanji" },
  "Hear": { ja: "きく", root: "聞", desc_ja: "聞くことに関連する漢字の部首", desc_en: "Radical for hear-related kanji" },
  "Use": { ja: "つかう", root: "用", desc_ja: "使うことに関連する漢字の部首", desc_en: "Radical for use-related kanji" },
  "Enter": { ja: "いる", root: "入", desc_ja: "入ることに関連する漢字の部首", desc_en: "Radical for enter-related kanji" },
  "Exit": { ja: "でる", root: "出", desc_ja: "出ることに関連する漢字の部首", desc_en: "Radical for exit-related kanji" },
  "Up": { ja: "うえ", root: "上", desc_ja: "上に関連する漢字の部首", desc_en: "Radical for up-related kanji" },
  "Down": { ja: "した", root: "下", desc_ja: "下に関連する漢字の部首", desc_en: "Radical for down-related kanji" },
  "Left": { ja: "ひだり", root: "左", desc_ja: "左に関連する漢字の部首", desc_en: "Radical for left-related kanji" },
  "Right": { ja: "みぎ", root: "右", desc_ja: "右に関連する漢字の部首", desc_en: "Radical for right-related kanji" },
  "Front": { ja: "まえ", root: "前", desc_ja: "前に関連する漢字の部首", desc_en: "Radical for front-related kanji" },
  "Back": { ja: "うしろ", root: "後", desc_ja: "後ろに関連する漢字の部首", desc_en: "Radical for back-related kanji" },
  "Inside": { ja: "なか", root: "内", desc_ja: "内側に関連する漢字の部首", desc_en: "Radical for inside-related kanji" },
  "Outside": { ja: "そと", root: "外", desc_ja: "外側に関連する漢字の部首", desc_en: "Radical for outside-related kanji" },
  "East": { ja: "ひがし", root: "東", desc_ja: "東に関連する漢字の部首", desc_en: "Radical for east-related kanji" },
  "West": { ja: "にし", root: "西", desc_ja: "西に関連する漢字の部首", desc_en: "Radical for west-related kanji" },
  "South": { ja: "みなみ", root: "南", desc_ja: "南に関連する漢字の部首", desc_en: "Radical for south-related kanji" },
  "North": { ja: "きた", root: "北", desc_ja: "北に関連する漢字の部首", desc_en: "Radical for north-related kanji" },
  "Spring": { ja: "はる", root: "春", desc_ja: "春に関連する漢字の部首", desc_en: "Radical for spring-related kanji" },
  "Summer": { ja: "なつ", root: "夏", desc_ja: "夏に関連する漢字の部首", desc_en: "Radical for summer-related kanji" },
  "Autumn": { ja: "あき", root: "秋", desc_ja: "秋に関連する漢字の部首", desc_en: "Radical for autumn-related kanji" },
  "Winter": { ja: "ふゆ", root: "冬", desc_ja: "冬に関連する漢字の部首", desc_en: "Radical for winter-related kanji" },
  "Morning": { ja: "あさ", root: "朝", desc_ja: "朝に関連する漢字の部首", desc_en: "Radical for morning-related kanji" },
  "Night": { ja: "よる", root: "夜", desc_ja: "夜に関連する漢字の部首", desc_en: "Radical for night-related kanji" },
  "Day": { ja: "ひ", root: "日", desc_ja: "日に関連する漢字の部首", desc_en: "Radical for day-related kanji" },
  "Year": { ja: "とし", root: "年", desc_ja: "年に関連する漢字の部首", desc_en: "Radical for year-related kanji" },
  "Time": { ja: "とき", root: "時", desc_ja: "時間に関連する漢字の部首", desc_en: "Radical for time-related kanji" },
  "Old": { ja: "ふるい", root: "古", desc_ja: "古いことに関連する漢字の部首", desc_en: "Radical for old-related kanji" },
  "New": { ja: "あたらしい", root: "新", desc_ja: "新しいことに関連する漢字の部首", desc_en: "Radical for new-related kanji" },
  "Long": { ja: "ながい", root: "長", desc_ja: "長さに関連する漢字の部首", desc_en: "Radical for long-related kanji" },
  "Short": { ja: "みじかい", root: "短", desc_ja: "短さに関連する漢字の部首", desc_en: "Radical for short-related kanji" },
  "High": { ja: "たかい", root: "高", desc_ja: "高さに関連する漢字の部首", desc_en: "Radical for high-related kanji" },
  "Low": { ja: "ひくい", root: "低", desc_ja: "低さに関連する漢字の部首", desc_en: "Radical for low-related kanji" },
  "Wide": { ja: "ひろい", root: "広", desc_ja: "広さに関連する漢字の部首", desc_en: "Radical for wide-related kanji" },
  "Narrow": { ja: "せまい", root: "狭", desc_ja: "狭さに関連する漢字の部首", desc_en: "Radical for narrow-related kanji" },
  "Heavy": { ja: "おもい", root: "重", desc_ja: "重さに関連する漢字の部首", desc_en: "Radical for heavy-related kanji" },
  "Light": { ja: "かるい", root: "軽", desc_ja: "軽さに関連する漢字の部首", desc_en: "Radical for light-related kanji" },
  "Hot": { ja: "あつい", root: "熱", desc_ja: "熱さに関連する漢字の部首", desc_en: "Radical for hot-related kanji" },
  "Cold": { ja: "つめたい", root: "冷", desc_ja: "冷たさに関連する漢字の部首", desc_en: "Radical for cold-related kanji" },
  "Fast": { ja: "はやい", root: "速", desc_ja: "速さに関連する漢字の部首", desc_en: "Radical for fast-related kanji" },
  "Slow": { ja: "おそい", root: "遅", desc_ja: "遅さに関連する漢字の部首", desc_en: "Radical for slow-related kanji" },
  "Hard": { ja: "かたい", root: "硬", desc_ja: "硬さに関連する漢字の部首", desc_en: "Radical for hard-related kanji" },
  "Soft": { ja: "やわらかい", root: "軟", desc_ja: "柔らかさに関連する漢字の部首", desc_en: "Radical for soft-related kanji" },
  "Strong": { ja: "つよい", root: "強", desc_ja: "強さに関連する漢字の部首", desc_en: "Radical for strong-related kanji" },
  "Weak": { ja: "よわい", root: "弱", desc_ja: "弱さに関連する漢字の部首", desc_en: "Radical for weak-related kanji" },
  "Bright": { ja: "あかるい", root: "明", desc_ja: "明るさに関連する漢字の部首", desc_en: "Radical for bright-related kanji" },
  "Dark": { ja: "くらい", root: "暗", desc_ja: "暗さに関連する漢字の部首", desc_en: "Radical for dark-related kanji" },
  "Good": { ja: "よい", root: "良", desc_ja: "良いことに関連する漢字の部首", desc_en: "Radical for good-related kanji" },
  "Bad": { ja: "わるい", root: "悪", desc_ja: "悪いことに関連する漢字の部首", desc_en: "Radical for bad-related kanji" },
  "Beautiful": { ja: "うつくしい", root: "美", desc_ja: "美しさに関連する漢字の部首", desc_en: "Radical for beautiful-related kanji" },
  "Ugly": { ja: "みにくい", root: "醜", desc_ja: "醜さに関連する漢字の部首", desc_en: "Radical for ugly-related kanji" },
  "True": { ja: "まこと", root: "真", desc_ja: "真実に関連する漢字の部首", desc_en: "Radical for true-related kanji" },
  "False": { ja: "いつわり", root: "偽", desc_ja: "偽りに関連する漢字の部首", desc_en: "Radical for false-related kanji" },
  "Life": { ja: "いのち", root: "生", desc_ja: "生命に関連する漢字の部首", desc_en: "Radical for life-related kanji" },
  "Die": { ja: "しぬ", root: "死", desc_ja: "死に関連する漢字の部首", desc_en: "Radical for die-related kanji" },
  "Love": { ja: "あい", root: "愛", desc_ja: "愛に関連する漢字の部首", desc_en: "Radical for love-related kanji" },
  "Hate": { ja: "にくむ", root: "憎", desc_ja: "憎しみに関連する漢字の部首", desc_en: "Radical for hate-related kanji" },
  "Happy": { ja: "たのしい", root: "楽", desc_ja: "楽しさに関連する漢字の部首", desc_en: "Radical for happy-related kanji" },
  "Sad": { ja: "かなしい", root: "悲", desc_ja: "悲しみに関連する漢字の部首", desc_en: "Radical for sad-related kanji" },
  "Angry": { ja: "おこる", root: "怒", desc_ja: "怒りに関連する漢字の部首", desc_en: "Radical for angry-related kanji" },
  "Fear": { ja: "おそれ", root: "恐", desc_ja: "恐れに関連する漢字の部首", desc_en: "Radical for fear-related kanji" },
  "Think": { ja: "おもう", root: "思", desc_ja: "思考に関連する漢字の部首", desc_en: "Radical for think-related kanji" },
  "Know": { ja: "しる", root: "知", desc_ja: "知識に関連する漢字の部首", desc_en: "Radical for know-related kanji" },
  "Learn": { ja: "まなぶ", root: "学", desc_ja: "学習に関連する漢字の部首", desc_en: "Radical for learn-related kanji" },
  "Teach": { ja: "おしえる", root: "教", desc_ja: "教育に関連する漢字の部首", desc_en: "Radical for teach-related kanji" },
  "Read": { ja: "よむ", root: "読", desc_ja: "読むことに関連する漢字の部首", desc_en: "Radical for read-related kanji" },
  "Write": { ja: "かく", root: "書", desc_ja: "書くことに関連する漢字の部首", desc_en: "Radical for write-related kanji" },
  "Make": { ja: "つくる", root: "作", desc_ja: "作ることに関連する漢字の部首", desc_en: "Radical for make-related kanji" },
  "Break": { ja: "こわす", root: "壊", desc_ja: "壊すことに関連する漢字の部首", desc_en: "Radical for break-related kanji" },
  "Open": { ja: "あける", root: "開", desc_ja: "開くことに関連する漢字の部首", desc_en: "Radical for open-related kanji" },
  "Close": { ja: "とじる", root: "閉", desc_ja: "閉じることに関連する漢字の部首", desc_en: "Radical for close-related kanji" },
  "Begin": { ja: "はじめる", root: "始", desc_ja: "始めることに関連する漢字の部首", desc_en: "Radical for begin-related kanji" },
  "End": { ja: "おわる", root: "終", desc_ja: "終わることに関連する漢字の部首", desc_en: "Radical for end-related kanji" },
  "Give": { ja: "あたえる", root: "与", desc_ja: "与えることに関連する漢字の部首", desc_en: "Radical for give-related kanji" },
  "Take": { ja: "とる", root: "取", desc_ja: "取ることに関連する漢字の部首", desc_en: "Radical for take-related kanji" },
  "Buy": { ja: "かう", root: "買", desc_ja: "買うことに関連する漢字の部首", desc_en: "Radical for buy-related kanji" },
  "Sell": { ja: "うる", root: "売", desc_ja: "売ることに関連する漢字の部首", desc_en: "Radical for sell-related kanji" },
  "Work": { ja: "はたらく", root: "働", desc_ja: "働くことに関連する漢字の部首", desc_en: "Radical for work-related kanji" },
  "Rest": { ja: "やすむ", root: "休", desc_ja: "休むことに関連する漢字の部首", desc_en: "Radical for rest-related kanji" },
  "Play": { ja: "あそぶ", root: "遊", desc_ja: "遊ぶことに関連する漢字の部首", desc_en: "Radical for play-related kanji" },
  "Fight": { ja: "たたかう", root: "戦", desc_ja: "戦うことに関連する漢字の部首", desc_en: "Radical for fight-related kanji" },
  "Win": { ja: "かつ", root: "勝", desc_ja: "勝つことに関連する漢字の部首", desc_en: "Radical for win-related kanji" },
  "Lose": { ja: "まける", root: "負", desc_ja: "負けることに関連する漢字の部首", desc_en: "Radical for lose-related kanji" },
  "Wait": { ja: "まつ", root: "待", desc_ja: "待つことに関連する漢字の部首", desc_en: "Radical for wait-related kanji" },
  "Move": { ja: "うごく", root: "動", desc_ja: "動くことに関連する漢字の部首", desc_en: "Radical for move-related kanji" },
  "Change": { ja: "かわる", root: "変", desc_ja: "変わることに関連する漢字の部首", desc_en: "Radical for change-related kanji" },
  "Same": { ja: "おなじ", root: "同", desc_ja: "同じことに関連する漢字の部首", desc_en: "Radical for same-related kanji" },
  "Different": { ja: "ちがう", root: "違", desc_ja: "違うことに関連する漢字の部首", desc_en: "Radical for different-related kanji" },
  "Together": { ja: "いっしょ", root: "共", desc_ja: "一緒に関連する漢字の部首", desc_en: "Radical for together-related kanji" },
  "Alone": { ja: "ひとり", root: "独", desc_ja: "一人に関連する漢字の部首", desc_en: "Radical for alone-related kanji" },
  "Friend": { ja: "とも", root: "友", desc_ja: "友達に関連する漢字の部首", desc_en: "Radical for friend-related kanji" },
  "Enemy": { ja: "てき", root: "敵", desc_ja: "敵に関連する漢字の部首", desc_en: "Radical for enemy-related kanji" },
  "Family": { ja: "かぞく", root: "家", desc_ja: "家族に関連する漢字の部首", desc_en: "Radical for family-related kanji" },
  "Father": { ja: "ちち", root: "父", desc_ja: "父に関連する漢字の部首", desc_en: "Radical for father-related kanji" },
  "Mother": { ja: "はは", root: "母", desc_ja: "母に関連する漢字の部首", desc_en: "Radical for mother-related kanji" },
  "Brother": { ja: "きょうだい", root: "兄", desc_ja: "兄弟に関連する漢字の部首", desc_en: "Radical for brother-related kanji" },
  "Sister": { ja: "しまい", root: "姉", desc_ja: "姉妹に関連する漢字の部首", desc_en: "Radical for sister-related kanji" },
  "Husband": { ja: "おっと", root: "夫", desc_ja: "夫に関連する漢字の部首", desc_en: "Radical for husband-related kanji" },
  "Wife": { ja: "つま", root: "妻", desc_ja: "妻に関連する漢字の部首", desc_en: "Radical for wife-related kanji" },
  "Son": { ja: "むすこ", root: "息", desc_ja: "息子に関連する漢字の部首", desc_en: "Radical for son-related kanji" },
  "Daughter": { ja: "むすめ", root: "娘", desc_ja: "娘に関連する漢字の部首", desc_en: "Radical for daughter-related kanji" },
  "God": { ja: "かみ", root: "神", desc_ja: "神に関連する漢字の部首", desc_en: "Radical for god-related kanji" },
  "Heaven": { ja: "てん", root: "天", desc_ja: "天に関連する漢字の部首", desc_en: "Radical for heaven-related kanji" },
  "Hell": { ja: "じごく", root: "獄", desc_ja: "地獄に関連する漢字の部首", desc_en: "Radical for hell-related kanji" },
  "King": { ja: "おう", root: "王", desc_ja: "王に関連する漢字の部首", desc_en: "Radical for king-related kanji" },
  "Queen": { ja: "じょおう", root: "后", desc_ja: "女王に関連する漢字の部首", desc_en: "Radical for queen-related kanji" },
  "Country": { ja: "くに", root: "国", desc_ja: "国に関連する漢字の部首", desc_en: "Radical for country-related kanji" },
  "City": { ja: "まち", root: "市", desc_ja: "市に関連する漢字の部首", desc_en: "Radical for city-related kanji" },
  "Village": { ja: "むら", root: "村", desc_ja: "村に関連する漢字の部首", desc_en: "Radical for village-related kanji" },
  "School": { ja: "がっこう", root: "校", desc_ja: "学校に関連する漢字の部首", desc_en: "Radical for school-related kanji" },
  "Temple": { ja: "てら", root: "寺", desc_ja: "寺に関連する漢字の部首", desc_en: "Radical for temple-related kanji" },
  "Shrine": { ja: "じんじゃ", root: "社", desc_ja: "神社に関連する漢字の部首", desc_en: "Radical for shrine-related kanji" },
  "Hospital": { ja: "びょういん", root: "院", desc_ja: "病院に関連する漢字の部首", desc_en: "Radical for hospital-related kanji" },
  "Station": { ja: "えき", root: "駅", desc_ja: "駅に関連する漢字の部首", desc_en: "Radical for station-related kanji" },
  "Bridge": { ja: "はし", root: "橋", desc_ja: "橋に関連する漢字の部首", desc_en: "Radical for bridge-related kanji" },
  "Tower": { ja: "とう", root: "塔", desc_ja: "塔に関連する漢字の部首", desc_en: "Radical for tower-related kanji" },
  "Wall": { ja: "かべ", root: "壁", desc_ja: "壁に関連する漢字の部首", desc_en: "Radical for wall-related kanji" },
  "Floor": { ja: "ゆか", root: "床", desc_ja: "床に関連する漢字の部首", desc_en: "Radical for floor-related kanji" },
  "Window": { ja: "まど", root: "窓", desc_ja: "窓に関連する漢字の部首", desc_en: "Radical for window-related kanji" },
  "Stool": { ja: "いす", root: "椅", desc_ja: "椅子に関連する漢字の部首", desc_en: "Radical for stool-related kanji" },
  "Table": { ja: "つくえ", root: "机", desc_ja: "机に関連する漢字の部首", desc_en: "Radical for table-related kanji" },
  "Book": { ja: "ほん", root: "本", desc_ja: "本に関連する漢字の部首", desc_en: "Radical for book-related kanji" },
  "Paper": { ja: "かみ", root: "紙", desc_ja: "紙に関連する漢字の部首", desc_en: "Radical for paper-related kanji" },
  "Pen": { ja: "ふで", root: "筆", desc_ja: "筆に関連する漢字の部首", desc_en: "Radical for pen-related kanji" },
  "Brush": { ja: "ふで", root: "筆", desc_ja: "筆に関連する漢字の部首", desc_en: "Radical for brush-related kanji" },
  "Picture": { ja: "え", root: "絵", desc_ja: "絵に関連する漢字の部首", desc_en: "Radical for picture-related kanji" },
  "Song": { ja: "うた", root: "歌", desc_ja: "歌に関連する漢字の部首", desc_en: "Radical for song-related kanji" },
  "Dance": { ja: "おどる", root: "舞", desc_ja: "舞に関連する漢字の部首", desc_en: "Radical for dance-related kanji" },
  "Sport": { ja: "スポーツ", root: "競", desc_ja: "スポーツに関連する漢字の部首", desc_en: "Radical for sport-related kanji" },
  "Game": { ja: "ゲーム", root: "戯", desc_ja: "ゲームに関連する漢字の部首", desc_en: "Radical for game-related kanji" },
  "Money": { ja: "おかね", root: "金", desc_ja: "お金に関連する漢字の部首", desc_en: "Radical for money-related kanji" },
  "Treasure": { ja: "たから", root: "宝", desc_ja: "宝に関連する漢字の部首", desc_en: "Radical for treasure-related kanji" },
  "Price": { ja: "ねだん", root: "価", desc_ja: "価格に関連する漢字の部首", desc_en: "Radical for price-related kanji" },
  "Trade": { ja: "ぼうえき", root: "易", desc_ja: "貿易に関連する漢字の部首", desc_en: "Radical for trade-related kanji" },
  "Law": { ja: "ほう", root: "法", desc_ja: "法律に関連する漢字の部首", desc_en: "Radical for law-related kanji" },
  "War": { ja: "せんそう", root: "戦", desc_ja: "戦争に関連する漢字の部首", desc_en: "Radical for war-related kanji" },
  "Peace": { ja: "へいわ", root: "和", desc_ja: "平和に関連する漢字の部首", desc_en: "Radical for peace-related kanji" },
  "Army": { ja: "ぐんたい", root: "軍", desc_ja: "軍隊に関連する漢字の部首", desc_en: "Radical for army-related kanji" },
  "Gun": { ja: "てっぽう", root: "銃", desc_ja: "銃に関連する漢字の部首", desc_en: "Radical for gun-related kanji" },
  "Medicine": { ja: "くすり", root: "薬", desc_ja: "薬に関連する漢字の部首", desc_en: "Radical for medicine-related kanji" },
  "Illness": { ja: "びょうき", root: "病", desc_ja: "病気に関連する漢字の部首", desc_en: "Radical for illness-related kanji" },
  "Pain": { ja: "いたみ", root: "痛", desc_ja: "痛みに関連する漢字の部首", desc_en: "Radical for pain-related kanji" },
  "Wound": { ja: "きず", root: "傷", desc_ja: "傷に関連する漢字の部首", desc_en: "Radical for wound-related kanji" },
  "Cure": { ja: "なおす", root: "治", desc_ja: "治療に関連する漢字の部首", desc_en: "Radical for cure-related kanji" },
  "Birth": { ja: "うまれる", root: "生", desc_ja: "誕生に関連する漢字の部首", desc_en: "Radical for birth-related kanji" },
  "Pregnant": { ja: "にんしん", root: "妊", desc_ja: "妊娠に関連する漢字の部首", desc_en: "Radical for pregnant-related kanji" },
  "Grow": { ja: "そだつ", root: "育", desc_ja: "成長に関連する漢字の部首", desc_en: "Radical for grow-related kanji" },
  "Age": { ja: "としをとる", root: "老", desc_ja: "年齢に関連する漢字の部首", desc_en: "Radical for age-related kanji" },
  "Eat": { ja: "たべる", root: "食", desc_ja: "食べることに関連する漢字の部首", desc_en: "Radical for eat-related kanji" },
  "Drink": { ja: "のむ", root: "飲", desc_ja: "飲むことに関連する漢字の部首", desc_en: "Radical for drink-related kanji" },
  "Sleep": { ja: "ねる", root: "眠", desc_ja: "眠ることに関連する漢字の部首", desc_en: "Radical for sleep-related kanji" },
  "Wake": { ja: "おきる", root: "覚", desc_ja: "起きることに関連する漢字の部首", desc_en: "Radical for wake-related kanji" },
  "Cloth": { ja: "ぬの", root: "布", desc_ja: "布に関連する漢字の部首", desc_en: "Radical for cloth-related kanji" },
  "Lid": { ja: "ふた", root: "蓋", desc_ja: "蓋に関連する漢字の部首", desc_en: "Radical for lid-related kanji" },
  "Box": { ja: "はこ", root: "箱", desc_ja: "箱に関連する漢字の部首", desc_en: "Radical for box-related kanji" },
  "Circle": { ja: "まる", root: "円", desc_ja: "円に関連する漢字の部首", desc_en: "Radical for circle-related kanji" },
  "Square": { ja: "しかく", root: "方", desc_ja: "四角に関連する漢字の部首", desc_en: "Radical for square-related kanji" },
  "Triangle": { ja: "さんかく", root: "三", desc_ja: "三角に関連する漢字の部首", desc_en: "Radical for triangle-related kanji" },
  "Line": { ja: "せん", root: "線", desc_ja: "線に関連する漢字の部首", desc_en: "Radical for line-related kanji" },
  "Dot": { ja: "てん", root: "点", desc_ja: "点に関連する漢字の部首", desc_en: "Radical for dot-related kanji" },
  "Grain": { ja: "つぶ", root: "粒", desc_ja: "粒に関連する漢字の部首", desc_en: "Radical for grain-related kanji" },
  "Drop": { ja: "しずく", root: "滴", desc_ja: "滴に関連する漢字の部首", desc_en: "Radical for drop-related kanji" },
  "Ice": { ja: "こおり", root: "氷", desc_ja: "氷に関連する漢字の部首", desc_en: "Radical for ice-related kanji" },
  "Steam": { ja: "じょうき", root: "蒸", desc_ja: "蒸気に関連する漢字の部首", desc_en: "Radical for steam-related kanji" },
  "Smoke": { ja: "けむり", root: "煙", desc_ja: "煙に関連する漢字の部首", desc_en: "Radical for smoke-related kanji" },
  "Cloud": { ja: "くも", root: "雲", desc_ja: "雲に関連する漢字の部首", desc_en: "Radical for cloud-related kanji" },
  "Star": { ja: "ほし", root: "星", desc_ja: "星に関連する漢字の部首", desc_en: "Radical for star-related kanji" },
  "Planet": { ja: "わくせい", root: "惑", desc_ja: "惑星に関連する漢字の部首", desc_en: "Radical for planet-related kanji" },
  "Sky": { ja: "そら", root: "空", desc_ja: "空に関連する漢字の部首", desc_en: "Radical for sky-related kanji" },
  "Ground": { ja: "じめん", root: "地", desc_ja: "地面に関連する漢字の部首", desc_en: "Radical for ground-related kanji" },
  "Cliff": { ja: "がけ", root: "崖", desc_ja: "崖に関連する漢字の部首", desc_en: "Radical for cliff-related kanji" },
  "Cave": { ja: "ほらあな", root: "洞", desc_ja: "洞窟に関連する漢字の部首", desc_en: "Radical for cave-related kanji" },
  "Valley": { ja: "たに", root: "谷", desc_ja: "谷に関連する漢字の部首", desc_en: "Radical for valley-related kanji" },
  "Forest": { ja: "もり", root: "森", desc_ja: "森に関連する漢字の部首", desc_en: "Radical for forest-related kanji" },
  "Leaf": { ja: "は", root: "葉", desc_ja: "葉に関連する漢字の部首", desc_en: "Radical for leaf-related kanji" },
  "Root": { ja: "ね", root: "根", desc_ja: "根に関連する漢字の部首", desc_en: "Radical for root-related kanji" },
  "Seed": { ja: "たね", root: "種", desc_ja: "種に関連する漢字の部首", desc_en: "Radical for seed-related kanji" },
  "Fruit": { ja: "くだもの", root: "果", desc_ja: "果物に関連する漢字の部首", desc_en: "Radical for fruit-related kanji" },
  "Vegetable": { ja: "やさい", root: "菜", desc_ja: "野菜に関連する漢字の部首", desc_en: "Radical for vegetable-related kanji" },
  "Meat": { ja: "にく", root: "肉", desc_ja: "肉に関連する漢字の部首", desc_en: "Radical for meat-related kanji" },
  "Egg": { ja: "たまご", root: "卵", desc_ja: "卵に関連する漢字の部首", desc_en: "Radical for egg-related kanji" },
  "Milk": { ja: "ちち", root: "乳", desc_ja: "乳に関連する漢字の部首", desc_en: "Radical for milk-related kanji" },
  "Oil": { ja: "あぶら", root: "油", desc_ja: "油に関連する漢字の部首", desc_en: "Radical for oil-related kanji" },
  "Salt": { ja: "しお", root: "塩", desc_ja: "塩に関連する漢字の部首", desc_en: "Radical for salt-related kanji" },
  "Sugar": { ja: "さとう", root: "糖", desc_ja: "砂糖に関連する漢字の部首", desc_en: "Radical for sugar-related kanji" },
  "Spice": { ja: "スパイス", root: "辛", desc_ja: "スパイスに関連する漢字の部首", desc_en: "Radical for spice-related kanji" },
  "Tea": { ja: "ちゃ", root: "茶", desc_ja: "茶に関連する漢字の部首", desc_en: "Radical for tea-related kanji" },
  "Wine": { ja: "ワイン", root: "酒", desc_ja: "ワインに関連する漢字の部首", desc_en: "Radical for wine-related kanji" },
  "Pot": { ja: "なべ", root: "鍋", desc_ja: "鍋に関連する漢字の部首", desc_en: "Radical for pot-related kanji" },
  "Dish": { ja: "さら", root: "皿", desc_ja: "皿に関連する漢字の部首", desc_en: "Radical for dish-related kanji" },
  "Cup": { ja: "コップ", root: "杯", desc_ja: "コップに関連する漢字の部首", desc_en: "Radical for cup-related kanji" },
  "Spoon": { ja: "さじ", root: "匙", desc_ja: "匙に関連する漢字の部首", desc_en: "Radical for spoon-related kanji" },
  "Fork": { ja: "フォーク", root: "叉", desc_ja: "フォークに関連する漢字の部首", desc_en: "Radical for fork-related kanji" },
  "Chopsticks": { ja: "はし", root: "箸", desc_ja: "箸に関連する漢字の部首", desc_en: "Radical for chopsticks-related kanji" },
  "Flag": { ja: "はた", root: "旗", desc_ja: "旗に関連する漢字の部首", desc_en: "Radical for flag-related kanji" },
  "Bell": { ja: "かね", root: "鐘", desc_ja: "鐘に関連する漢字の部首", desc_en: "Radical for bell-related kanji" },
  "Drum": { ja: "たいこ", root: "鼓", desc_ja: "太鼓に関連する漢字の部首", desc_en: "Radical for drum-related kanji" },
  "Flute": { ja: "ふえ", root: "笛", desc_ja: "笛に関連する漢字の部首", desc_en: "Radical for flute-related kanji" },
  "Harp": { ja: "たてごと", root: "琴", desc_ja: "琴に関連する漢字の部首", desc_en: "Radical for harp-related kanji" },
  "Mirror": { ja: "かがみ", root: "鏡", desc_ja: "鏡に関連する漢字の部首", desc_en: "Radical for mirror-related kanji" },
  "Needle": { ja: "はり", root: "針", desc_ja: "針に関連する漢字の部首", desc_en: "Radical for needle-related kanji" },
  "Wheel": { ja: "わ", root: "輪", desc_ja: "車輪に関連する漢字の部首", desc_en: "Radical for wheel-related kanji" },
  "Key": { ja: "かぎ", root: "鍵", desc_ja: "鍵に関連する漢字の部首", desc_en: "Radical for key-related kanji" },
  "Lock": { ja: "じょう", root: "錠", desc_ja: "錠前に関連する漢字の部首", desc_en: "Radical for lock-related kanji" },
  "Chain": { ja: "くさり", root: "鎖", desc_ja: "鎖に関連する漢字の部首", desc_en: "Radical for chain-related kanji" },
  "Rope": { ja: "なわ", root: "縄", desc_ja: "縄に関連する漢字の部首", desc_en: "Radical for rope-related kanji" },
  "Net": { ja: "あみ", root: "網", desc_ja: "網に関連する漢字の部首", desc_en: "Radical for net-related kanji" },
  "Tent": { ja: "テント", root: "幕", desc_ja: "テントに関連する漢字の部首", desc_en: "Radical for tent-related kanji" },
  "Umbrella": { ja: "かさ", root: "傘", desc_ja: "傘に関連する漢字の部首", desc_en: "Radical for umbrella-related kanji" },
  "Shoe": { ja: "くつ", root: "靴", desc_ja: "靴に関連する漢字の部首", desc_en: "Radical for shoe-related kanji" },
  "Hat": { ja: "ぼうし", root: "帽", desc_ja: "帽子に関連する漢字の部首", desc_en: "Radical for hat-related kanji" },
  "Bag": { ja: "かばん", root: "袋", desc_ja: "袋に関連する漢字の部首", desc_en: "Radical for bag-related kanji" },
  "Towel": { ja: "タオル", root: "巾", desc_ja: "タオルに関連する漢字の部首", desc_en: "Radical for towel-related kanji" },
  "Soap": { ja: "せっけん", root: "皂", desc_ja: "石鹸に関連する漢字の部首", desc_en: "Radical for soap-related kanji" },
  "Axe": { ja: "おの", root: "斤", desc_ja: "斧に関連する漢字の部首", desc_en: "Radical for axe-related kanji" },
  "Hammer": { ja: "つち", root: "槌", desc_ja: "ハンマーに関連する漢字の部首", desc_en: "Radical for hammer-related kanji" },
  "Saw": { ja: "のこぎり", root: "鋸", desc_ja: "鋸に関連する漢字の部首", desc_en: "Radical for saw-related kanji" },
  "Nail": { ja: "くぎ", root: "釘", desc_ja: "釘に関連する漢字の部首", desc_en: "Radical for nail-related kanji" },
  "Screw": { ja: "ねじ", root: "螺", desc_ja: "ネジに関連する漢字の部首", desc_en: "Radical for screw-related kanji" },
  "Ladder": { ja: "はしご", root: "梯", desc_ja: "はしごに関連する漢字の部首", desc_en: "Radical for ladder-related kanji" },
  "Stairs": { ja: "かいだん", root: "階", desc_ja: "階段に関連する漢字の部首", desc_en: "Radical for stairs-related kanji" },
  "Elevator": { ja: "エレベーター", root: "昇", desc_ja: "エレベーターに関連する漢字の部首", desc_en: "Radical for elevator-related kanji" },
  "Pipe": { ja: "パイプ", root: "管", desc_ja: "パイプに関連する漢字の部首", desc_en: "Radical for pipe-related kanji" },
  "Wire": { ja: "はりがね", root: "線", desc_ja: "ワイヤーに関連する漢字の部首", desc_en: "Radical for wire-related kanji" },
  "Electric": { ja: "でんき", root: "電", desc_ja: "電気に関連する漢字の部首", desc_en: "Radical for electric-related kanji" },
  "Machine": { ja: "きかい", root: "機", desc_ja: "機械に関連する漢字の部首", desc_en: "Radical for machine-related kanji" },
  "Engine": { ja: "エンジン", root: "機", desc_ja: "エンジンに関連する漢字の部首", desc_en: "Radical for engine-related kanji" },
  "Fuel": { ja: "ねんりょう", root: "燃", desc_ja: "燃料に関連する漢字の部首", desc_en: "Radical for fuel-related kanji" },
  "Gas": { ja: "ガス", root: "気", desc_ja: "ガスに関連する漢字の部首", desc_en: "Radical for gas-related kanji" },
  "Plastic": { ja: "プラスチック", root: "塑", desc_ja: "プラスチックに関連する漢字の部首", desc_en: "Radical for plastic-related kanji" },
  "Glass": { ja: "ガラス", root: "硝", desc_ja: "ガラスに関連する漢字の部首", desc_en: "Radical for glass-related kanji" },
  "Steel": { ja: "はがね", root: "鋼", desc_ja: "鋼に関連する漢字の部首", desc_en: "Radical for steel-related kanji" },
  "Iron": { ja: "てつ", root: "鉄", desc_ja: "鉄に関連する漢字の部首", desc_en: "Radical for iron-related kanji" },
  "Copper": { ja: "どう", root: "銅", desc_ja: "銅に関連する漢字の部首", desc_en: "Radical for copper-related kanji" },
  "Silver": { ja: "ぎん", root: "銀", desc_ja: "銀に関連する漢字の部首", desc_en: "Radical for silver-related kanji" },
  "Bronze": { ja: "ブロンズ", root: "青銅", desc_ja: "ブロンズに関連する漢字の部首", desc_en: "Radical for bronze-related kanji" },
  "Diamond": { ja: "ダイヤモンド", root: "鑽", desc_ja: "ダイヤモンドに関連する漢字の部首", desc_en: "Radical for diamond-related kanji" },
  "Pearl": { ja: "しんじゅ", root: "珠", desc_ja: "真珠に関連する漢字の部首", desc_en: "Radical for pearl-related kanji" },
  "Coral": { ja: "さんご", root: "珊", desc_ja: "サンゴに関連する漢字の部首", desc_en: "Radical for coral-related kanji" },
  "Crystal": { ja: "すいしょう", root: "晶", desc_ja: "水晶に関連する漢字の部首", desc_en: "Radical for crystal-related kanji" },
  "Jade": { ja: "ヒスイ", root: "翠", desc_ja: "翡翠に関連する漢字の部首", desc_en: "Radical for jade-related kanji" },
  "Amber": { ja: "こはく", root: "琥", desc_ja: "琥珀に関連する漢字の部首", desc_en: "Radical for amber-related kanji" },
  "Above": { ja: "うえ", root: "上", desc_ja: "上に関連する漢字の部首", desc_en: "Radical for above-related kanji" },
  "Below": { ja: "した", root: "下", desc_ja: "下に関連する漢字の部首", desc_en: "Radical for below-related kanji" },
  "Accept": { ja: "うけいれる", root: "受", desc_ja: "受け入れに関連する漢字の部首", desc_en: "Radical for accept-related kanji" },
  "Again": { ja: "また", root: "又", desc_ja: "再びに関連する漢字の部首", desc_en: "Radical for again-related kanji" },
  "Angel": { ja: "てんし", root: "天", desc_ja: "天使に関連する漢字の部首", desc_en: "Radical for angel-related kanji" },
  "Angle": { ja: "かど", root: "角", desc_ja: "角度に関連する漢字の部首", desc_en: "Radical for angle-related kanji" },
  "Animal": { ja: "どうぶつ", root: "獣", desc_ja: "動物に関連する漢字の部首", desc_en: "Radical for animal-related kanji" },
  "Announce": { ja: "しらせる", root: "告", desc_ja: "告知に関連する漢字の部首", desc_en: "Radical for announce-related kanji" },
  "Anti": { ja: "はんたい", root: "反", desc_ja: "反対に関連する漢字の部首", desc_en: "Radical for anti-related kanji" },
  "Bar": { ja: "ぼう", root: "棒", desc_ja: "棒に関連する漢字の部首", desc_en: "Radical for bar-related kanji" },
  "Barb": { ja: "とげ", root: "刺", desc_ja: "とげに関連する漢字の部首", desc_en: "Radical for barb-related kanji" },
  "Beans": { ja: "まめ", root: "豆", desc_ja: "豆に関連する漢字の部首", desc_en: "Radical for beans-related kanji" },
  "Become": { ja: "なる", root: "成", desc_ja: "成ることに関連する漢字の部首", desc_en: "Radical for become-related kanji" },
  "Belt": { ja: "おび", root: "帯", desc_ja: "帯に関連する漢字の部首", desc_en: "Radical for belt-related kanji" },
  "Ability": { ja: "のうりょく", root: "能", desc_ja: "能力に関連する漢字の部首", desc_en: "Radical for ability-related kanji" },
};

async function main() {
  const dictPath = path.join(process.cwd(), "data", "kanji-dictionary.json");
  const outputPath = path.join(process.cwd(), "data", "radicals_bilingual.json");
  
  // 辞書データを読み込み
  console.log("[*] Loading kanji dictionary...");
  const dictionary: KanjiDetail[] = JSON.parse(fs.readFileSync(dictPath, "utf-8"));
  
  // 全部首を抽出
  const radicalSet = new Set<string>();
  dictionary.forEach((k) => k.radicals?.forEach((r) => radicalSet.add(r)));
  const allRadicals = Array.from(radicalSet).sort();
  
  console.log(`[*] Found ${allRadicals.length} unique radicals`);
  
  // バイリンガルデータを生成
  const bilingualData: RadicalBilingual[] = allRadicals.map((radical, index) => {
    const mapping = RADICAL_NAME_MAP[radical];
    
    if (mapping) {
      return {
        id: index + 1,
        root: mapping.root,
        radical_name_en: radical,
        radical_name_ja: mapping.ja,
        description_en: mapping.desc_en,
        description_ja: mapping.desc_ja,
      };
    } else {
      // マッピングがない場合はデフォルト値を使用
      return {
        id: index + 1,
        root: radical.charAt(0),
        radical_name_en: radical,
        radical_name_ja: radical,
        description_en: `Radical related to ${radical.toLowerCase()} kanji`,
        description_ja: `${radical}に関連する漢字の部首`,
      };
    }
  });
  
  // JSONファイルとして保存
  console.log(`[*] Saving to ${outputPath}...`);
  fs.writeFileSync(outputPath, JSON.stringify(bilingualData, null, 2), "utf-8");
  
  console.log(`\n✅ radicals_bilingual.json generated (${bilingualData.length} entries)`);
}

main().catch(console.error);

